#!/bin/bash

# Function to add a new secret
add_secret() {
    local secret_name=$1
    
    # Add the new secret to secrets.nix
    sed -i '' "/^}/i\\
\"$secret_name\".publicKeys = [kevin];" secrets.nix
    
    # Open the new secret file in the default editor
    EDITOR=micro nix run github:ryantm/agenix -- -e "$secret_name"
    
    # Stage the changes
    git add secrets.nix "$secret_name"
    
    echo "Secret $secret_name added successfully."
}

# Main script
echo "Navigating to nix-secrets repository..."
cd ~/nix-secrets || exit

echo "Pulling latest changes..."
git pull

secrets_added=()

while true; do
    echo "Enter the name of the new secret (e.g., test.age):"
    read -r secret_name
    
    add_secret "$secret_name"
    secrets_added+=("$secret_name")
    
    echo "Do you want to add another secret? (y/n)"
    read -r answer
    if [[ $answer != "y" ]]; then
        break
    fi
done

# Commit all changes
if [ ${#secrets_added[@]} -eq 1 ]; then
    commit_message="Add secret: ${secrets_added[0]}"
else
    commit_message="Add secrets: ${secrets_added[*]}"
fi

git commit -m "$commit_message"

echo "Pushing changes..."
git push

# Navigate to nixos-config repository and update
echo "Updating nixos-config..."
cd ~/nixos-config || exit
git pull
nix flake update

echo "All secrets have been added and nixos-config has been updated."
echo "You can now test the new secret(s) using:"
echo "nix run github:ryantm/agenix -- -d <secret_name>"

# List added secrets
echo "Secrets added in this session:"
for secret in "${secrets_added[@]}"; do
    echo "- $secret"
done